### PR TITLE
Don't really need to concat..

### PR DESCRIPTION
**Pull request by Maxamed**

### CODE REVIEW

**Comment by Maxamed** [comment]
..............

**Comment by andyjamesdavies** [comment]
it's best to leave the grunt file alone, yes, you don't really need to concat as well, but sometimes I do separately for debugging purposes. Thanks

**Comment by Maxamed** [comment]
No problem other than that it's a nice library , pass my regards to Kevin he kept telling me about it :)

**Comment by andyjamesdavies** [comment]
Will do, thanks :)

**Pull request closed without merging**
